learning_log/learning_log/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import  include,url
urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^users/',include('users.urls',namespace='users')),
    url(r'',include('learning_logs.urls',namespace='learning_logs')),

]

learning_log/learning_logs/urls.py
"""定义learning_logs的URL模式"""
from django.conf.urls import url
from . import views
app_name='learning_logs'
urlpatterns=[
    url(r'^topics/$',views.index,name='topics'),
    url(r'^$',views.index,name='index'),
    url(r'^topics/(?P<topic_id>\d+)/$',views.topic,name='topic'),
    url(r'^new_topic/$',views.new_topic,name='new_topic'),
    url(r'^new_entry/(?P<topic_id>\d+)/$',views.new_entry,name='new_entry'),
    #用于编辑条目的页面
    url(r'^edit/(?P<entry_id>\d+)/$',views.edit_entry,name='edit_entry'), #URL模式
       ]

learning_log/users/urls.py
"""为应用程序users定义URL模式"""
from django.conf.urls import url
from django.contrib.auth.views import login #导入默认视图
from . import views
app_name='users'
urlpatterns=[
    #登陆页面
    url(r'^login/$',login,{'template_name':'users/login.html'},name='login'),
    url(r'^logout/$',views.logout_view,name='logout'),
    url(r'register/$',views.register,name='register'),
]

learning_log/learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Topic(models.Model):
    """用户学习的主题"""
    text=models.CharField(max_length=200) #该属性存储少量文本
    date_added=models.DateTimeField(auto_now_add=True) #将此属性设为当前的日期和时间
    owner=models.ForeignKey(User,on_delete=models.CASCADE)
    def __str__(self):
        """返回模型的字符串表示"""
        return self.text
class Entry(models.Model): #添加条目定义模型
    topic=models.ForeignKey(Topic,on_delete=models.CASCADE)
    text=models.TextField()
    date_added=models.DateTimeField(auto_now_add=True)
    class Meta:
        verbose_name_plural='entries'
    def __str__(self):
        """返回模型的字符串表示"""
        return  self.text[:50]+"..."

learning_log/users/models.py
from django.db import models

# Create your models here.

learning_log/learning_logs/forms.py
from django import forms
from .models import Topic,Entry
class TopicForm(forms.ModelForm):
    class Meta:
        model=Topic
        fields=['text']
        labels={'text':''}
class EntryForm(forms.ModelForm):
    class Meta:
        model=Entry
        fields = ['text']
        labels = {'text': ''}
        widgets={'text':forms.Textarea(attrs={'cols':80})} #文本区域的宽度设为80列，而不是默认的40列

learning_log/learning_logs/views.py
from django.shortcuts import render
from .models import Topic
from django.http import HttpResponsePermanentRedirect,Http404
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Topic,Entry
from .forms import TopicForm,EntryForm
from django.contrib.auth.decorators import login_required
# Create your views here.
def index(request):
    return render(request,'learning_logs/index.html')
@login_required
def topics(request):
    """显示所有主题"""
    topics=Topic.objects.filter(owner=request.user).order_by('date_added')
    topics=Topic.objects.order_by('date_added')
    context={'topics:topics'}
    return render(request,'learning_logs/topics.html',context)
@login_required
def topic(request,topic_id):
    """显示  单个主题及所有条目"""
    topic=Topic.objects.get(id=topic_id)
    #确认请求的主题属于当前用户
    if topic.owner != request.user:
       raise Http404
    entries=topic.entry_set.order_by('-date_added')
    context={'topic':topic,'entries':entries}
    return render(request,'learning_logs/topic.html',context)
@login_required
def new_topic(request):
    """添加新主题"""
    if request.method != 'POST':
      #未提交数据，创建新表单
      form=TopicForm()
    else:
      #创建新表单
      form=TopicForm(request.POST)
      if form.is_valid():
          new_topic=form.save(commit=False)
          new_topic.owner=request.user
          new_topic.save()
          return HttpResponseRedirect(reverse('learning_logs:topics'))
    context={'form':form}
    return render(request,'learning_logs/new_topic.html',context)
@login_required
def new_entry(request,topic_id):
    """在特定的主题中添加新条目"""
    topic=Topic.objects.get(id=topic_id)
    if request.method !='POST':
        form=EntryForm()
        if form.is_valid():
            new_entry=form.save(commit=False)
            new_entry.topic=topic
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_Logs:topic',args=[topic_id]))
    context={'topic':topic,'form':form}
    return (request,'learning_logs/new_entry.html',context)
@login_required
def edit_entry(request,entry_id):
    """编辑既有条目"""
    entry=Entry.objects.get(id=entry_id)
    topic=entry.topic
    if topic.owner!=request.user:
        raise Http404
    if request.method !='POST':
        #初次请求，使用当前条目填充表单!
        form=EntryForm(instance=entry)
    else:
        #POST提交的数据，对数据进行处理
        form=EntryForm(instance=entry)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topic',args=[topic]))
    context={'entry':entry,'topic':topic,'form':form}
    return render(request,'learning_logs/edit_entry.html',context)

learning_log/users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import logout,login,authenticate
# Create your views here.
def logout_view(request):
    """注销用户"""
    logout(request)
    return HttpResponseRedirect(reverse('learning_logs:index'))
def register(request):
    """注册新用户!"""
    if request.method !='POST':
        #显示空的注册表单
        form=UserCreationForm()
    else:
        #处理填好的表单
        form=UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user=form.save()
            #让用户自动登陆，再重定向到主页
            authenticated_user=authenticate(username=new_user.username,password=request.POST['password1'])
            login(request,authenticated_user)
            return HttpResponseRedirect(reverse('learning_logs:index'))
        context={'form':form }
        return render(request,'users/register.html',context)

learning_log/learning_logs/templates/learning_logs/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
<p>
    <a href="{% url 'learning_logs:index' %}">Learning Log</a>-
    <a href="{% url 'learning_logs:topics' %}">Topics</a>
    {% if user.is_authenticated %}
      Hello,{{ user.username }}.
      <a href="{% url 'users:logout' %}">log out</a>
    {% else %}
    <a href="{% url 'users:register' %}">register</a>
    <a href="{% url 'users:login' %}">log in</a>
    {% endif %}
</p>
{% block content %} {%endblock content %}
</body>
</html>

learning_log/learning_logs/templates/learning_logs/edit_entry.html

{% extends "learning_logs/base.html" %}

{% block content %}

  <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>
    
  <p>Edit entry:</p>
    
  <form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">save changes</button>
  </form>

{% endblock content %}

learning_log/learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}
{% block content %}
<p>
    Learning Log helps you keep track of your learning,for any topics you are learning about!
</p>
{% endblock content %}

learning_log/learning_logs/templates/learning_logs/new_entry.html

{% extends "learning_logs/base.html" %}

{% block content %}

  <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>
    
  <p>Add a new entry:</p>
  <form action="{% url 'learning_logs:new_entry' topic.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name='submit'>add entry</button>
  </form>
    
{% endblock content %}

learning_log/learning_logs/templates/learning_logs/new_topic.html

{% extends "learning_logs/base.html" %}

{% block content %}
  <p>Add a new topic:</p>

  <form action="{% url 'learning_logs:new_topic' %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">add topic</button>
  </form>
    
{% endblock content %}

learning_log/learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block content %}

  <p>Topic: {{ topic }}</p>

  <p>Entries:</p>
<p>
  <a href="{% url 'learning_logs:new_entry' topic.id %}">Add new Entry</a>
</p>
  <ul>
  {% for entry in entries %}
    <li>
      <p>{{ entry.date_added|date:'M d, Y H:i' }}</p>
      <p>{{ entry.text|linebreaks }}</p>
        <p>
            <a href="{% url 'learning_logs:edit_entry' entry.id %}">edit entry </a>
        </p>
    </li>
  {% empty %}
    <li>
      There are no entries for this topic yet.
    </li>
  {% endfor %}
  </ul>

{% endblock content %}

learning_log/learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block content %}

  <p>Topics</p>

  <ul>
    {% for topic in topics %}
      <li>
        <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
	  </li>
    {% empty %}
      <li>No topics have been added yet.</li>
    {% endfor %}
  </ul>
<a href="{% url 'learning_logs:new_topic' %}">Add a new topic!</a>
{% endblock content %}

learning_log/users/templates/users/login.html

{% extends "learning_logs/base.html" %}

{% block content %}

  {% if form.errors %}
    <p>Your username and password didn't match. Please try again.</p>
  {% endif %}
    
  <form method="post" action="{% url 'users:login' %}">
    {% csrf_token %}
    {{ form.as_p }}
    
    <button name="submit">log in</button>
    <input type="hidden" name="next"
      value="{% url 'learning_logs:index' %}" />
  </form>
    
{% endblock content %}

learning_log/users/templates/users/register.html
{% extends "learning_logs/base.html" %}
{% block content %}
<form method="post" action="{% url 'users:register' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">register</button>
    <input type="hidden" name="text" value="{% url 'learning_logs:index'%}"/>
</form>
{% endblock content %}